# Generated by Django 5.1.3 on 2024-11-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationName', models.CharField(max_length=25, unique=True)),
                ('organizationEmail', models.EmailField(max_length=25)),
                ('organizationWebsite', models.URLField()),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('educationLevel', models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=50, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
